site_name: Fellowship Dungeon RTFM
site_description: Cliff notes for Fellowship Dungeons
site_url: https://Disc0rdantMel0dy.github.io/FellowshipRTFM/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - toc.follow
plugins:
  - search
markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - md_in_html 
  - toc:
      permalink: true
extra_javascript:
  - assets/target-blank.js
extra_css:
  - assets/two-col.css
  - assets/wide-content.css
  - attr_list
nav:
  - Home: index.md
  - Normal Dungeons:
      - Sailor's Abyss: dungeons/sailors_abyss.md
      - Everdawn Grove: dungeons/everdawn_grove.md
      - Silken Hollow: dungeons/silken_hollow.md
      - Godfall Quarry: dungeons/godfall_quarry.md
      - Empyrean Sands: dungeons/empyrean_sands.md
      - Urrak Markets: dungeons/urrak_markets.md
  - Capstone Dungeons:
      - Cithrel's Fall (Contender League): dungeons/cithrels_fall.md
      - The Heart of Tuzari (Adept League): dungeons/the_heart_of_tuzari.md
      - Wraithtide Vault (Champion League): dungeons/wraithtide_vault.md
      - Ransack of Drakheim (Paragon League): dungeons/ransack_of_drakheim.md
